# Continuous Integration
name: CI

# Only will run when there is a commit or a pull request in the master branch (to be changed)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

        # Go environment check out (not needed for now till tests run)
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.1

        # Build of Business-Handler binary
      - name: Building Business-Handler binary
        run: |
          cd BusinessHandler
          go build -o canITravelToBusinessHandler

        # Build of Data-Retriever binary
      - name: Building Data-Retriever binary
        run: |
          cd DataRetriever
          go build -o canITravelToDataRetriever
        # Decrypts credentials needed to build the docker image
      - name: Decrypt Creds
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output BusinessHandler/Creds/creds.json BusinessHandler/Creds/creds.json.gpg
          chmod 600 BusinessHandler/Creds/creds.json
          gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output DataRetriever/Creds/creds.json DataRetriever/Creds/creds.json.gpg
          chmod 600 DataRetriever/Creds/creds.json
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

        # Test of Business-Handler
      - name: Testing Business-Handler
        run: |
          cd BusinessHandler/Tests/Controller
          go test -password=$DB_PASSWORD
          cd ../Utils
          go test
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        # Test of Data-Retriever
      - name: Testing Data-Retriever
        run: |
          cd DataRetriever/Tests
          go test -password=$DB_PASSWORD
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
